### PR TITLE
Don't let own props shadow Relay props

### PR DESCRIPTION
**Pull request by taion**
Fixes https://github.com/4Catalyzer/found-relay/issues/104

### CODE REVIEW

**Comment by taion** [comment]
Ready to go now.

**Comment by johntran** [comment]
```
Ignoring <ReadyStateRenderer> prop `viewer` that shadows a Relay prop from its query `UNKNOWN`. This is most likely due to its parent cloning it and adding extraneous Relay props.
```

So how would one get rid of this warning?

**Comment by taion** [comment]
@johntran

It's happening in your code because `<AppComponent>` is passing down `viewer` to `<Main>`, which then passes it down to its `page`.

Does doing so serve a specific purpose for you? The `viewer` that `<Main>` passes down to its `page` can and should get shadowed anyway, so it's not doing anything here. It didn't look like your `<Main>` was using that `viewer` prop, either.

**Comment by johntran** [comment]
That fixed it. Thanks! 

The `viewer` being passed down to `<Main>` was extraneous. Removing it got rid of the console.error.

**Comment by taion** [comment]
BTW, that also fixes things with alphas 7 through 9. The change in alpha 10 is just to drop it and warn.

Any other concerns here or should I merge and release?

**Comment by johntran** [comment]
No concerns left. Ship it 👍

**Comment by taion** [comment]
released alpha 10

**Pull request merged**
